# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34bd145bd7c7976f2b0bdfce9d84270463956cad48eb3fef0633e2110a581fcce147ff744df2f4637b45c1c8487498536141f2738c147ab1e8f5219ddca9308

test:
  secret_key_base: 0d3c2128e90156a037c7fbf4158bca6f7108b0670a118a7b793f0644b448df6af0b3c4dad9cceb165152ebcfd26d0e3d4610ec4b718c4557600cadd0833c5e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
